### ISSUE TITLE
用 :hover？

### ISSUE THREAD

**Issue by Equim-chan** [MaoKwen/hexo-black-cover#2]
现在这个设置，要选定这些文字才能看到内容。而萌娘百科上的只要鼠标滑过即可。

如果可以的话，设置一下 CSS 的 :hover 属性，看起来会方便些w

**Comment by MaoKwen** [comment]
@Equim-chan 交给你了...

**Comment by Equim-chan** [comment]
我……我其实是个后端，对这个不熟呢…

**Comment by MaoKwen** [comment]
我是个学生.. 博客也是早就没有了.. 你可以试试这个, 看起来不错 https://github.com/unnamed42/hexo-spoiler

**Comment by MaoKwen** [comment]
@Equim-chan 试试看能用吗
